# Project: julia4d
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = julia5b2b.o $(RES)
LINKOBJ  = julia5b2b.o $(RES)
LIBS =  -L"d:/Dev-Cpp/lib" -lmingw32 -lSDLmain -lSDL  
INCS =  -I"d:/Dev-Cpp/include" 
CXXINCS =  -I"d:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"d:/Dev-Cpp/include/c++/3.4.2/backward"  -I"d:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"d:/Dev-Cpp/include/c++/3.4.2"  -I"d:/Dev-Cpp/include" 
BIN  = julia4d.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before julia4d.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "julia4d.exe" $(LIBS)

julia5b2b.o: julia5b2b.cpp
	$(CPP) -c julia5b2b.cpp -o julia5b2b.o $(CXXFLAGS)
